name: Build Firefox on Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Install MozillaBuild
        run: choco install mozillabuild -y
          
      - name: Bootstrap Mozilla Source
        working-directory: C:\
        shell: C:\mozilla-build\start-shell.bat -here -e {0}
        run: |
          mkdir mozilla-source
          cd mozilla-source
          wget --tries=5 https://hg.mozilla.org/mozilla-central/raw-file/default/python/mozboot/bin/bootstrap.py
          python3 bootstrap.py --application-choice=browser --no-interactive

      - name: Update Local Source
        working-directory: C:\mozilla-source\mozilla-unified
        shell: C:\mozilla-build\start-shell.bat -here -e {0}
        run: hg up -C central

      - name: Initialize `mozconfig`
        working-directory: C:\mozilla-source\mozilla-unified
        shell: C:\mozilla-build\start-shell.bat -here -e {0}
        run: echo "ac_add_options --with-branding=browser/branding/official" > mozconfig

      - name: Build and Package
        working-directory: C:\mozilla-source\mozilla-unified
        shell: C:\mozilla-build\start-shell.bat -here -e {0}
        run: |
          ./mach build
          ./mach package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-firefox-artifacts
          path: "C:/mozilla-source/mozilla-unified/obj-x86_64-pc-windows-msvc/dist/install/sea"
          
